#Nombre de la acción
name: Integracion continua

# Sección de eventos que activan el flujo de trabajo
# Aquí se activa cuando se hace un push al repositorio
on: 
  push

# Permisos para el flujo de trabajo
jobs:
    compilar-ejecutar:
        runs-on: ubuntu-22.04
        steps:
          - name: Clonar repositorio
            uses: actions/checkout@v4
        
          - name: Compilar código
            run: gcc ejercicios.c -o ejercicios
          - name: Ejecutar programa
            run: ./ejercicios
          
          - name: Compilar código listas ligadas
            run: listasLigadas.c -o ejelistasligada
          - name: Ejecutar programa listas ligadas
            run: ./ejelistasligada